package org.example;

public enum ConditionType {
    FRONT_IS_CLEAR,
    FRONT_IS_BLOCKED,
    LEFT_IS_CLEAR,
    LEFT_IS_BLOCKED,
    RIGHT_IS_CLEAR,
    RIGHT_IS_BLOCKED,
    BEEPERS_PRESENT,
    NO_BEEPERS_PRESENT,
    BEEPERS_IN_BAG,
    NO_BEEPERS_IN_BAG,
    FACING_NORTH,
    NOT_FACING_NORTH,
    FACING_EAST,
    NOT_FACING_EAST,
    FACING_SOUTH,
    NOT_FACING_SOUTH,
    FACING_WEST,
    NOT_FACING_WEST
}
