DROP TABLE IF EXISTS karel.SUBMISSIONS;
DROP TABLE IF EXISTS karel.TESTS;
DROP TABLE IF EXISTS karel.PROBLEMS;
DROP TABLE IF EXISTS karel.USERS;
DROP TABLE IF EXISTS karel.STATUSES;
DROP SCHEMA KAREL;